sampling_time: 0.0
refresh_rate: 0.0
output_name: kapton_daq
instruments:
  thermometer:
    type: multimeter
    make: slac
    model: Thermometer
    comm:
      type: serial
      args:
        port: /dev/ttyUSB0
        baud: 115200
    measurements:
      temperature_0:
        quantity: temperature_probe_0
        unit: celsius
        name: Temperature0
      temperature_1:
        quantity: temperature_probe_1
        unit: celsius
        name: Temperature1
      temperature_2:
        quantity: temperature_probe_2
        unit: celsius
        name: Temperature2
      temperature_3:
        quantity: temperature_probe_3
        unit: celsius
        name: Temperature3